In [1]:
import numpy as np

a=np.array(9)

print("Print A= ",a)

b=np.array([100,200,300])

print("Print B= ", b)

addition= np.add(a,b)

print("After Addition =", addition)

sub=np.subtract(b,a)

print("After Subtraction =",sub)

mul=np.multiply (a,b)

print("After Multiplcation =",mul)

div=np.divide (b,a)

print("After Division =",div)

div1=np.divide (b,5)

print("After Division =",div1)

Print A=  9
Print B=  [100 200 300]
After Addition = [109 209 309]
After Subtraction = [ 91 191 291]
After Multiplcation = [ 900 1800 2700]
After Division = [11.11111111 22.22222222 33.33333333]
After Division = [20. 40. 60.]


In [4]:
#reciprocal

a= np.array([0.20,0.25,0.33,0.16])

print(a)

rec=np.reciprocal(a) 
print(rec)

[0.2  0.25 0.33 0.16]
[5.         4.         3.03030303 6.25      ]


In [3]:
a=np.array([10,100,1000])

print(a)

pow=np.power(a,2)
print("after ^2 = ", pow)


b=np.array([2,3,1])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)


[  10  100 1000]
after ^2 =  [    100   10000 1000000]
after b array elements as ^ =  [    100 1000000    1000]


In [5]:
a= np.array ([49,216,30])
b= np.array ([7,8,9])

print("values of A=", a)
print("values of B=", b)

mm=np.mod(a,b)

rm=np.remainder(a,b)

print("values of MOD=", mm)
print("values of REMAINDER=", rm)



values of A= [ 49 216  30]
values of B= [7 8 9]
values of MOD= [0 0 3]
values of REMAINDER= [0 0 3]


In [20]:
a=np.array([-5.6j, 0.2j,11, 1+1j])
print(a)

print("real=",np.real(a))

print("imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))

[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [26]:
a=np.array ([1.0,5.3,123,0.56,25.5,32])

print(a)

print("after rounding up=", np.around(a))

print("after rounding up to 1st decimal value =", np.around(a,decimals=1))

[  1.     5.3  123.     0.56  25.5   32.  ]
after rounding up= [  1.   5. 123.   1.  26.  32.]
after rounding up to 1st decimal value = [  1.    5.3 123.    0.6  25.5  32. ]


In [6]:
a=np.array ([4.9,-8.4,321,-0.65,52.5,96])

print(a)

print('\n')

print(np.floor(a))

print(np.ceil(a))

[  4.9   -8.4  321.    -0.65  52.5   96.  ]


[  4.  -9. 321.  -1.  52.  96.]
[  5.  -8. 321.  -0.  53.  96.]
